Transporter/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TransporterModel;
using TransporterCore;
using InstamojoAPI;
using GenericHelper;
using System.Configuration;
using System.Web.Script.Serialization;

namespace Transporter.Controllers
{
    public class SubscriptionController : BaseController
    {
        // GET: Subsription
        public ActionResult Index()
        {
            UserSubscription returnObj = new UserSubscription();
            returnObj.StartDate = ((User)Session["User"]).ValidFrom.ToString("dd-MMM-yyyy");
            returnObj.EndDate = ((User)Session["User"]).ValidTo.ToString("dd-MMM-yyyy");
            //returnObj.Type = ((User)Session["User"]).UserTypeID.ToString();
            returnObj.Type = Enum.GetName(typeof(AllEnums.UserType), ((User)Session["User"]).UserTypeID).ToString();
            return View(returnObj);
        }

        private ClientPaymentInitiate InitPaymentObj(int Duration, int Type)
        {
            ClientPaymentInitiate Model = new ClientPaymentInitiate();
            User refObj = (User)Session["User"];

            Model.UserFullName = (refObj.FirstName.ToString() + " " + (refObj.LastName.ToString()));
            Model.UserEmail = refObj.Email.ToString();
            Model.UserID = refObj.UserID;
            Model.UserTypeID = refObj.UserTypeID;
            Model.UserMobileNumber = refObj.MobileNumber.ToString();
            Model.PaymentTransactionID = refObj.UserID.ToString() + DateTime.Now.ToString("yyyymmddhhmmss"); // Guid.NewGuid().ToString();
            Model.PaymentInitiateDateFrom = DateTime.Now.ToString("dd-mmm-yyyy");  //("dd-mmm-yyyy h:mm tt");
            Model.PaymentInitiateDateTo = DateTime.Now.AddMonths(Duration).ToString("dd-mmm-yyyy");
            Model.PaymentAmount = ((Duration == 1) ? 10 : 12).ToString();//((Duration == 1) ? 1000 : 10000).ToString(); // TODO: This is for test the payment gateway purposes, will need to revert to 1000 and 10000 
            Model.PaymentCurrency = "INR";
            Model.PaymentInitiateTypeID = Convert.ToInt32(Type.ToString() + Duration.ToString());
            return Model;
        }

        public ActionResult ShowPayment(int Duration, int Type)
        {
            return PartialView("_ShowPayment", InitPaymentObj(Duration, Type));
        }

        [HttpPost]
        public JsonResult InitPayment(int Duration, int Type)
        {
            AjaxReturnData returnVal = new AjaxReturnData();
            returnVal.UniqueId = 0;
            returnVal.IsSuccess = false;
            returnVal.Message = "";

            try
            {
                int InternalPaymentID = 0;
                string successPrompt = "You will be now redirected to a 3rd party website for payment, please do not close the browser until the payment is complete!";
                ClientPaymentInitiate Model = InitPaymentObj(Duration, Type);
                string Insta_client_id = ConfigurationManager.AppSettings["PayClientID"].ToString();
                string Insta_client_secret = ConfigurationManager.AppSettings["PayClientSecret"].ToString();
                string Insta_Endpoint = ConfigurationManager.AppSettings["PayEndPoint"].ToString();
                string Insta_Auth_Endpoint = ConfigurationManager.AppSettings["PayAuthEndPoint"].ToString();
                string Insta_redirectURL = ConfigurationManager.AppSettings["PaymentRedirect"].ToString();
                string Insta_webhook = ConfigurationManager.AppSettings["PaymentWebHook"].ToString();

                Instamojo objClass = InstamojoImplementation.getApi(Insta_client_id, Insta_client_secret, Insta_Endpoint, Insta_Auth_Endpoint);

                PaymentOrder objPaymentRequest = new PaymentOrder();
                //Required POST parameters
                objPaymentRequest.name = Model.UserFullName;
                objPaymentRequest.email = Model.UserEmail;
                objPaymentRequest.phone = Model.UserMobileNumber;
                objPaymentRequest.amount = Convert.ToDouble(Model.PaymentAmount);
                objPaymentRequest.currency = Model.PaymentCurrency; //"Unsupported"
                objPaymentRequest.transaction_id = Model.PaymentTransactionID;

                objPaymentRequest.redirect_url = Insta_redirectURL;
                objPaymentRequest.webhook_url = Insta_webhook + objPaymentRequest.transaction_id.ToString();

                SubscriptionBL updObj = new SubscriptionBL();
                updObj.UpsertPaymentDetails(((User)Session["User"]).UserID, ((User)Session["User"]).ValidFrom.ToString("dd-MMM-yyyy"), ((User)Session["User"]).ValidTo.ToString("dd-MMM-yyyy"), (Decimal)objPaymentRequest.amount,
                            objPaymentRequest.transaction_id, DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(),
                            DateTime.Now.ToString(), DateTime.Now.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), 1, DBNull.Value.ToString(), ref InternalPaymentID);


                if (objPaymentRequest.validate())
                {
                    try
                    {
                        CreatePaymentOrderResponse objPaymentResponse = objClass.createNewPaymentRequest(objPaymentRequest);
                        returnVal.Message = successPrompt;
                        returnVal.RedirectURL = objPaymentResponse.payment_options.payment_url.ToString();
                        returnVal.IsSuccess = true;

                        // Code to write the request and response object to the DB table:

                        updObj.UpsertPaymentDetails(((User)Session["User"]).UserID, ((User)Session["User"]).ValidFrom.ToString("dd-MMM-yyyy"), ((User)Session["User"]).ValidTo.ToString("dd-MMM-yyyy"), (Decimal)objPaymentRequest.amount,
                            objPaymentRequest.transaction_id, DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(),
                            DateTime.Now.ToString(), DateTime.Now.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), DBNull.Value.ToString(), 1, DBNull.Value.ToString(), ref InternalPaymentID);

                        return Json(returnVal, JsonRequestBehavior.AllowGet);
                        //MessageBox.Show("Order Id = " + objPaymentResponse.order.id);
                    }
                    //catch (ArgumentNullException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    //catch (WebException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    //catch (IOException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    //catch (InvalidPaymentOrderException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    //catch (ConnectionException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    //catch (BaseException ex)
                    //{
                    //    MessageBox.Show(ex.Message);
                    //}
                    catch (Exception ex)
                    {
                        //MessageBox.Show("Error:" + ex.Message);
                        throw ex;
                    }
                }
                else
                {
                    try
                    {
                        CreatePaymentOrderResponse objPaymentResponse = objClass.createNewPaymentRequest(objPaymentRequest);
                        returnVal.IsSuccess = true;
                        returnVal.Message = successPrompt;
                        returnVal.RedirectURL = objPaymentResponse.payment_options.payment_url.ToString();
                        updObj.UpsertPaymentDetails(((User)Session["User"]).UserID, ((User)Session["User"]).ValidFrom.ToString("dd-MMM-yyyy"), ((User)Session["User"]).ValidTo.ToString("dd-MMM-yyyy"), (Decimal)objPaymentRequest.amount,
                            objPaymentRequest.transaction_id, objPaymentResponse.order.id.ToString(), objPaymentRequest.redirect_url.ToString(), objPaymentResponse.order.webhook_url.ToString(),
                            objPaymentResponse.payment_options.payment_url.ToString(), DateTime.Now.ToString(), DateTime.Now.ToString(), DBNull.Value.ToString()
                            , DBNull.Value.ToString(), DBNull.Value.ToString(), 1, DBNull.Value.ToString(), ref InternalPaymentID);

                        return Json(returnVal, JsonRequestBehavior.AllowGet);
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                }
            }
            catch (Exception ex)
            {
                returnVal.Message = ex.Message;
                returnVal.IsSuccess = false;
                return Json(returnVal, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult PaymentAcknowledgement(string id, string transaction_id, string payment_id)
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult PaymentHistory()
        {
            UserPaymentHistory Model = new UserPaymentHistory();
            SubscriptionBL returnObj = new SubscriptionBL();
            string retVal = "";
            Model = returnObj.GetPaymentDetails(((User)Session["User"]).UserID, ((User)Session["User"]).UserID, ref retVal);
            if (retVal.ToUpper().Contains("ERROR"))
            {
                throw new Exception(retVal);
            }
            return View(Model);
        }


        //    [HttpPost]

Transporter/Views/Subscription/PaymentAcknowledgement.cshtml
@{
    ViewBag.Title = "Payment Acknowledgement";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<section class="section fp-table animateOut animateIn">
    <div class="fp-tableCell">
        <div class="container">
            <div class="page-body">
                <div class="row">
                    <div class="col-md-12 innerHeader">
                        <!--<h4>Dashboard</h4>-->
                        <div class="codepen-wrapper search-wrapper">  <span class="registration-ui"> <i class="fa fa-ban leftsrew"></i>Payment Acknowledgement<i class="fa fa-ban rightsrew"></i></span>  </div>
                        <hr>
                        <div class="card searchCard">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12">
                                    <div class="form-group row">
                                        <label for="example-text-input" class="col-md-12 col-form-label text-left">Thank you for your payment initiation!! </label>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12">
                                    <div class="form-group row">
                                        <label for="example-text-input" class="col-md-12 col-form-label text-left">It is normal to take 2 -3 business days for the payment to reflect in our site. We will however notify you via SMS and email once we have a payment confirmation</label>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Transporter/Views/Subscription/PaymentHistory.cshtml
`@{
    ViewBag.Title = "Payment History";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

@model TransporterModel.UserPaymentHistory

@using (Html.BeginForm("PaymentHistory", "Subscription", FormMethod.Post))
{
    <section class="section fp-table animateOut animateIn">
        <div class="fp-tableCell">
            <div class="container">
                <div class="page-body">
                    <div class="row">
                        <div class="col-md-12 innerHeader">
                            <!--<h4>Dashboard</h4>-->
                            <div class="codepen-wrapper search-wrapper">  <span class="registration-ui"> <i class="fa fa-ban leftsrew"></i>User Payment History<i class="fa fa-ban rightsrew"></i></span>  </div>
                            <hr>
                            <div class="card searchCard">
                                <div class="col-md-12">
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label text-right">User Name:</label>
                                            <div class="input-group">
                                                @Html.DisplayFor(m => m.UserName, new { @class = "form-control", @id = "lblUserName" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label text-right">Last Payment On:</label>
                                            <div class="input-group">
                                                @Html.DisplayFor(m => m.LastPaymentAttemptedOn, new { @class = "form-control", @id = "lblLastPaymentOn" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label text-right">Member Since:</label>
                                            <div class="input-group">
                                                @Html.DisplayFor(m => m.MemberSince, new { @class = "form-control", @id = "lblMemSince" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label text-right">Member Status:</label>
                                            <div class="input-group">
                                                @Html.DisplayFor(m => m.MemberStatus, new { @class = "form-control", @id = "lblMemStatus" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8 col-sm-12">
                                        <div class="form-group">
                                            <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("Index", "Subscription")';">Back to Subscription</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section fp-section fp-table animateOut animateIn">
        <div class="fp-tableCell">
            <div class="wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card margin-top-5">
                                <h5>Payment details: </h5>
                                <div class="card-block table-border-style">
                                    <div id="responsive-tbl">
                                        <table id="MyTable">
                                            <thead>
                                                <tr>
                                                    <th data-label="TransactionID">TransactionID</th>
                                                    <th data-label="InitiatedOn">Transaction Date</th>
                                                    <th data-label="AcknowledgementOn">Acknowledgement ReceivedOn</th>
                                                    <th data-label="PaymentStatus">Payment Status</th>
                                                    <th data-label="PaymentAmount">Amount</th>
                                                    <th data-label="CurrentExpiryDate">CurrentExpiryDate</th>
                                                    <th data-label="RequestingExpiryDate">RequestingExpiryDate</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model.PaymentDetails.Count > 0)
                                                {
                                                    for (var i = 0; i < Model.PaymentDetails.Count; i++)
                                                    {
                                                        var paymentData = Model.PaymentDetails[i];
                                                        <tr>
                                                            <td data-label="TransactionID"><a href='/Booking/Edit?bookingId=@paymentData.ExtTransactionID' class="customLink">@paymentData.ExtTransactionID</a></td>
                                                            <td data-label="InitiatedOn">@paymentData.InitiatedOn</td>
                                                            <td data-label="AcknowledgementOn">@paymentData.PaymentAcknowledgementReceivedOn</td>
                                                            <td data-label="PaymentStatus">@paymentData.PaymentStatusName</td>
                                                            <td data-label="PaymentAmount">@paymentData.PaymentAmount</td>
                                                            <td data-label="CurrentExpiryDate">@paymentData.CurrentExpiryDate</td>
                                                            <td data-label="RequestingExpiryDate">@paymentData.RequestedExpiryDate</td>
                                                        </tr>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}