Transporter/Controllers/AdminReportsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TransporterModel;
using TransporterCore;
using GenericHelper;

namespace Transporter.Admin.Controllers
{
    public class AdminReportsController : BaseAdminController
    {
        // GET: AdminReports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetUserRegistReport()
        {
            return View();
        }
        public ActionResult GetLoginTracking()
        {
            return GetGenericReportDetails("UserLogin report");
        }

        public ActionResult GetAReport(string reportName)
        {
            return GetGenericReportDetails(reportName);
        }

        private ActionResult GetGenericReportDetails(string reportName)
        {
           ReportSchema rpt = GetReportObj(reportName);
            FillDropDownsInViewBag(rpt);
            ViewBag.ReportName = reportName;
            ViewBag.DropDownDefault = Constants.PageTexts.DropdownDefaultSelect;

            return View("GenericReport", rpt);
        }

        private void FillDropDownsInViewBag(ReportSchema rpt)
        {
            PopulateMasters DDLMaster = new PopulateMasters();
            foreach(InputField inFld in rpt.InFields)
            {
                if(inFld.ValueType.ToUpper() == "DROPDOWN")
                {
                    if(inFld.ValueName.ToUpper() == "USERTYPE")
                    {
                        var ddlUserType = (
                            from result in DDLMaster.FetchUserType(0)
                            select new SelectListItem()
                            {
                                Text = result.UserTypeName,
                                Value = result.UserTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlUserType.Add(new SelectListItem() {Text ="Select All", Value="" });
                        ViewBag.ddlUserType = ddlUserType;
                    }
                    if (inFld.ValueName.ToUpper() == "GOODSTYPE")
                    {
                        var ddlGoodsType = (
                            from result in DDLMaster.FetchGoodsType(0)
                            select new SelectListItem()
                            {
                                Text = result.GoodsTypeName,
                                Value = result.GoodsTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlGoodsType.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlGoodsType = ddlGoodsType;
                    }
                    if (inFld.ValueName.ToUpper() == "GOODSWEIGHT")
                    {
                        var ddlGoodsWeight = (
                            from result in DDLMaster.FetchGoodsWeight(0)
                            select new SelectListItem()
                            {
                                Text = result.GoodsWeightName,
                                Value = result.GoodsWeightID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlGoodsWeight.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlGoodsWeight = ddlGoodsWeight;
                    }
                    if (inFld.ValueName.ToUpper() == "PACKAGETYPE")
                    {
                        var ddlPackageType = (
                            from result in DDLMaster.FetchPackageType(0)
                            select new SelectListItem()
                            {
                                Text = result.PackageTypeName,
                                Value = result.PackageTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlPackageType.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlPackageType = ddlPackageType;
                    }
                    if (inFld.ValueName.ToUpper() == "TRUCKTYPE")
                    {
                        var ddlTruckType = (
                            from result in DDLMaster.FetchTruckType(0)
                            select new SelectListItem()
                            {
                                Text = result.TruckTypeName,
                                Value = result.TruckTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlTruckType.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlTruckType = ddlTruckType;
                    }
                    if (inFld.ValueName.ToUpper() == "PAYMENTTYPE")
                    {
                        var ddlPaymentType = (
                            from result in DDLMaster.FetchPaymentType(0)
                            select new SelectListItem()
                            {
                                Text = result.PaymentTypeName,
                                Value = result.PaymentTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlPaymentType.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlPaymentType = ddlPaymentType;
                    }
                    if (inFld.ValueName.ToUpper() == "CITYNAME")
                    {
                        var ddlCityName = (
                            from result in DDLMaster.FetchCity(0)
                            select new SelectListItem()
                            {
                                Text = result.CityName,
                                Value = result.CityID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlCityName.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlCityName = ddlCityName;
                    }
                    if (inFld.ValueName.ToUpper() == "STATENAME")
                    {
                        var ddlStateName = (
                            from result in DDLMaster.FetchState(0)
                            select new SelectListItem()
                            {
                                Text = result.StateName,
                                Value = result.StateID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlStateName.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlStateName = ddlStateName;
                    }
                    if (inFld.ValueName.ToUpper() == "CITYNAME1")
                    {
                        var ddlCityName1 = (
                            from result in DDLMaster.FetchState(0)
                            select new SelectListItem()
                            {
                                Text = result.StateName,
                                Value = result.StateID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlCityName1.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlCityName1 = ddlCityName1;
                    }
                    if (inFld.ValueName.ToUpper() == "BOOKINGSTATUS")
                    {
                        var ddlBookingStatus = (
                            from result in DDLMaster.FetchBookingStatus(0)
                            select new SelectListItem()
                            {
                                Text = result.StatusName,
                                Value = result.StatusID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlBookingStatus.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlBookingStatus = ddlBookingStatus;
                    }
                    if (inFld.ValueName.ToUpper() == "POSTINGSTATUS")
                    {
                        var ddlPostingStatus = (
                            from result in DDLMaster.FetchPostingStatus(0)
                            select new SelectListItem()
                            {
                                Text = result.StatusName,
                                Value = result.StatusID.ToString(),
                                Selected = false
                            }
                        ).ToList();
                        ddlPostingStatus.Add(new SelectListItem() { Text = "Select All", Value = "" });
                        ViewBag.ddlPostingStatus = ddlPostingStatus;
                    }
                    if (inFld.ValueName.ToUpper() == "BUSINESSTYPE")
                    {
                        var ddlBusinessType = (
                            from result in DDLMaster.FetchBusinessType(0)
                            select new SelectListItem()
                            {
                                Text = result.BusinessTypeName,
                                Value = result.BusinessTypeID.ToString(),
                                Selected = false
                            }
                        ).ToList();

Transporter/Views/AdminReports/GenericReport.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

@model TransporterModel.ReportSchema

@using (Html.BeginForm("GetReportData", "AdminReports", FormMethod.Post, new { name = "GetReport", id = "GetReport" }))
{
    <section class="section fp-table animateOut animateIn">
        <div class="fp-tableCell">
            <div class="container">
                <div class="page-body">
                    <div class="row">
                        <div class="col-md-12 innerHeader">
                            <!--<h4>Dashboard</h4>-->
                            <div class="codepen-wrapper search-wrapper">  <span class="registration-ui"> <i class="fa fa-ban leftsrew"></i><label id="lblReportName">@Model.Name</label><i class="fa fa-ban rightsrew"></i></span>  </div>
                            <hr>
                            <div class="card searchCard">
                                    <div class="col-md-12">
                                    @for (int i = 0; i < Model.InFields.Count; i++)
                                    {
                                        if (i <= 2) // First 3 fields in first row
                                        {
                                            {Html.RenderPartial("_ReportControl", Model.InFields[i]);}
                                        }
                                    }
                                    </div>
                                <div class="col-md-12">
                                    @for (int i = 3; i < Model.InFields.Count; i++)
                                    {
                                        if (i <= 5) // Second 3 fields in first row
                                        {
                                            { Html.RenderPartial("_ReportControl", Model.InFields[i]); }
                                        }
                                    }
                                </div>

                                <div class="col-md-12">
                                    @for (int i = 6; i < Model.InFields.Count; i++)
                                    {
                                        if (i <= 8) // Third 3 fields in first row
                                        {
                                            { Html.RenderPartial("_ReportControl", Model.InFields[i]); }
                                        }
                                    }
                                </div>
                                
                                <div class="clearfix"></div>
                                <div class="col-md-12">
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group">
                                            <button type="button" class="btn btn-danger" onclick="SearchPost();">Search</button>
                                            <button type="button" class="btn btn-default" onclick="ClearSearch();">Clear</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section fp-section fp-table animateOut animateIn">
        <div class="fp-tableCell">
            <div class="wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card margin-top-5">
                                <h5>Search result : </h5>
                                <div class="card-block table-border-style">
                                    <div id="responsive-tbl">
                                        <table id="MyTable">
                                            <thead>
                                                <tr>
                                                    @for (int j = 0; j < Model.OutFields.OutFieldName.Count; j++)
                                                    {
                                                        <th data-label="@Model.OutFields.OutFieldName[j].ToString()">@Model.OutFields.OutFieldName[j].ToString()</th>
                                                    }                                                    
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>

            var demo1 = SetAutoComplete("#txtSourceCity", "#hdnSourceCity");

            var demo2 = SetAutoComplete("#txtDestinationCity", "#hdnDestinationCity");

            function ClearSearch() {
                ClearAllFormInputFields();
            }

            function getFormData($form) {
                var unindexed_array = $form.serializeArray();
                var indexed_array = {};

                $.map(unindexed_array, function (n, i) {
                    indexed_array[n['name']] = n['value'];
                });

                return indexed_array;
            }

            function SearchPost() {
                var formObj = getFormData($("#GetReport")); // Send formID as parameter
                //var data2Send = {};
                //var index = 0;
                //var unindexed_array = $("#GetReport").serializeArray();
                //$.map(unindexed_array, function (n, i) {
                //    //indexed_array[n['name']] = n['value'];
                //    data2Send["stepsDictionary[" + index + "].Key"] = n['name'];
                //    data2Send["stepsDictionary[" + index + "].Value"] = n['value'];
                //    index++;
                //});
                var theObject = {};
                theObject.dict = formObj;
                ReportName = $('#lblReportName').text();
                var data2send = { inputFields: theObject, reportName: ReportName }

                $.ajax({
                    type: "POST",
                    url: "/AdminReports/GetReportData",
                    data: JSON.stringify(data2send),
                    cache: false,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        
                        var IsSuccess = result.IsSuccess;
                        var msg = result.Message;
                        var url = result.RedirectURL;
                        
                        if (result.IsSucces === 'Failure') {
                            console.log('error', result);
                            modalPopup.SetText('Failure', '', result);
                        }
                        $("#MyTable tr:gt(0)").remove();
                        $('#MyTable').append(result.Message);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        LogAndShowAjaxError(thrownError, xhr.status);
                    }
                });
            }
    </script>
}

Transporter/Views/AdminReports/GetUserRegistReport.cshtml
@{
    ViewBag.Title = "GetUserRegistReport";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<h2>GetUserRegistReport</h2>

Transporter/Views/AdminReports/_MastersDropdown.cshtml
@model TransporterModel.InputField

@if (Model.ValueName.ToUpper() == "USERTYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlUserType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "GOODSTYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlGoodsType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "GOODSWEIGHT")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlGoodsWeight, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "PACKAGETYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlPackageType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "TRUCKTYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlTruckType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "PAYMENTTYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlPaymentType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "CITYNAME")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlCityName, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "CITYNAME1")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlCityName1, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "STATENAME")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlStateName, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "BOOKINGSTATUS")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlBookingStatus, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "POSTINGSTATUS")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlPostingStatus, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}
@if (Model.ValueName.ToUpper() == "BUSINESSTYPE")
{
    @Html.DropDownList(Model.ValueID.ToString(), new SelectList(ViewBag.ddlBusinessType, "Value", "Text"), new { @class = "form-control", id = Model.ValueID.ToString() });
}

Transporter/Views/AdminReports/_ReportControl.cshtml
@model TransporterModel.InputField
@if (Model.ValueType.ToUpper() == TransporterModel.FieldType.String.ToString().ToUpper())
{
    <div class="col-md-4 col-sm-12">
        <div class="form-group row">
            <label for="example-text-input" class="col-md-4 col-form-label text-right">@Model.LabelText</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-question-circle"></i></span>
                @Html.TextBox(Model.ValueID, null, new { @class = "form-control", @placeholder = Model.ValueFieldPlaceholder })
                @if (Model.HiddenID != "")
                {
                    @Html.HiddenFor(m => m.HiddenID, new { @id = Model.HiddenID })
                }
            </div>
        </div>
    </div>
}
@if (Model.ValueType.ToUpper() == TransporterModel.FieldType.DateTime.ToString().ToUpper())
{
    <div class="col-md-4 col-sm-12">
        <div class="form-group row">
            <label for="example-text-input" class="col-md-4 col-form-label text-right">@Model.LabelText</label>
            <div class="input-group date">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input type="text" class="form-control" placeholder="DD/MM/YYYY" id="@Model.ValueID" name="@Model.ValueID">
            </div>
        </div>
    </div>
}
@if (Model.ValueType.ToUpper() == TransporterModel.FieldType.DropDown.ToString().ToUpper())
{
    <div class="col-md-4 col-sm-12">
        <div class="form-group row">
            <label for="example-text-input" class="col-md-4 col-form-label text-right">@Model.LabelText</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                @Html.Partial("_MastersDropdown")
            </div>
        </div>
    </div>
}