Transporter/Controllers/TrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TransporterCore;
using TransporterModel;

namespace Transporter.Controllers
{
    public class TrackingController : BaseController
    {
        // GET: Tracking
        public ActionResult Index()
        {
            ViewBag.TrackingStatus = "100"; // 100- trip yet to start, 200-tripstarted, 300-load pickedup, 400-load intransit, 500-load dropped at dest, 600-tripcompleted
            ViewBag.TrackingMessage = "Trip sheet created but trip yet to start";

            ViewBag.CreateMode = false;

            int postingID = 0;
            int bookingID = 0;

            // Send loggedinUserID as SP param, so as to check if the logged in user is in any way associated to the trip
            if (Request["BookingID"] != null)
            {
                bookingID = Convert.ToInt32(Request["BookingID"].ToString());
            }

            if (Request["PostingID"] != null)
            {
                postingID = Convert.ToInt32(Request["PostingID"].ToString());
            }

            if(bookingID ==0 && postingID == 0)
            {
                return View();
            }

            TripSheet Model = new TripSheet();
            PostingCreateBL TripObj = new PostingCreateBL();
            int loggedInUser = ((User)Session["User"]).UserID;
            Model = TripObj.GetTripData(postingID, bookingID, loggedInUser);

            return View(Model);
        }

        public JsonResult GetTripGeoLocData(int postingID)
        {
            string result = "Failure";
            AjaxReturnData returnVal = new AjaxReturnData();
            returnVal.UniqueId = postingID;
            returnVal.IsSuccess = false;
            returnVal.Message = result;
            try
            {
                PostingCreateBL TripObj = new PostingCreateBL();
                TripTracking retObj = new TripTracking();
                retObj = TripObj.GetTripGeoLocData(postingID, ((User)Session["User"]).UserID);

                returnVal.UniqueId = postingID;
                returnVal.IsSuccess = true;
                returnVal.Message = Json(retObj).ToString();

                return Json(retObj, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                returnVal.Message = returnVal.Message + ex.Message;
                return Json(returnVal, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Transporter/Views/Tracking/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}
@model TransporterModel.TripSheet

@using (Html.BeginForm("Index", "Tracking", FormMethod.Post))
{
    <script>
        function SearchTripData(){
            var bookingID = $("#txtBookingID").val();
            var postingID = $("#txtPostingID").val();

            if(bookingID){
                if(postingID){
                    if(bookingID > 0 && postingID > 0){
                        modalPopup.SetText("Alert","", "Please enter only one of the two options to search");
                        return;
                    }
                }
            }

            if(!bookingID && !postingID){
                modalPopup.SetText("Alert","", "Please enter any one of the two options to search");
            }

            if(bookingID){
                window.location.href="/Tracking/Index?bookingID=" + bookingID;
            }
            if(postingID){
                window.location.href="/Tracking/Index?postingID=" + postingID;
            }
        }
    </script>
    <section class="section fp-table animateOut animateIn">
        <div class="fp-tableCell">
            <div class="container">
                <div class="page-body">
                    <div class="row">
                        <div class="col-md-12 innerHeader">
                            <!--<h4>Dashboard</h4>-->
                            <div class="codepen-wrapper cpd-wrapper">
                                <span class="create-post-details">
                                    <i class="fa fa-ban leftsrew"></i>View Booking/Posting tracking
                                    <i class="fa fa-ban rightsrew"></i>
                                </span>
                            </div>
                            <hr>
                            <div class="card searchCard">
                                <div class="row">
                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">Posting ID:</label>                                            
                                            <div class="input-group col-md-8 cpd-group">
                                                <span class="input-group-addon"><i class="fa fa-rou"></i><i class="fa fa-sticky-note"></i></span>
                                                <input type="number" id="txtPostingID" class="form-control" value="@Request.QueryString["PostingID"]"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">Booking ID:</label>                                            
                                            <div class="input-group col-md-8 cpd-group">
                                                <span class="input-group-addon"><i class="fa fa-rou"></i><i class="fa fa-sticky-note"></i></span>
                                                <input type="number" id="txtBookingID" class="form-control" value="@Request.QueryString["BookingID"]" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">Trip Status:</label>                                            
                                            <div class="input-group col-md-8 cpd-group">
                                                <span class="PageLabel" id="lblBookingStatus">
                                                    &nbsp;
                                                    @if (Model != null)
                                                    {
                                                        if (Model.PostingStatus > 0)
                                                        {
                                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">@Model.PostingStatusName.ToString()</label>
                                                        }
                                                        else
                                                        {
                                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">No data found</label>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <label for="example-text-input" class="col-md-4 col-form-label pull-left">No data found</label>
                                                    }
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12">
                                        <div class="form-group row">
                                            <label for="example-text-input" class="col-md-4 col-form-label pull-left">&nbsp;</label>
                                            <div class="input-group col-md-8 cpd-group">
                                                <button type="button" class="btn btn-success pull-right" onclick="SearchTripData();"><i class="fa fa-plus"></i> Search</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>

    if (Model != null && Model.TripBookingData != null)
    {
        @Html.Partial("~/Views/Posting/_TripData.cshtml", Model);
        <script>
            var postingIDVal = @Model.PostingID;
            $("#txtPostingID").val(postingIDVal);

            
        </script>
    }

}

Transporter/Views/Tracking/_VisualTracker.cshtml
@using System.Web.Script.Serialization;
@model TransporterModel.TripDetailFromPage
<script>
    var postingID = @Model.PostingID;
    var TripDetailsRaw =  '@(Html.Raw(new JavaScriptSerializer().Serialize(Model.TripTrackingDetails)))';

    var TripDetails = JSON.parse(TripDetailsRaw);
    // This example uses a symbol to add a vector-based icon to a marker.
    // The symbol uses one of the predefined vector paths ('CIRCLE') supplied by the
    // Google Maps JavaScript API.
    var tripData=[];
    var trackingData=[];
    $.each( TripDetails.TripData, function(i, obj) {
        tripData.push(TripDetails.TripData[i])
    });
    $.each(TripDetails.TruckTrackingData, function(i, obj) {
        trackingData.push(TripDetails.TruckTrackingData[i])
    });

        console.log("--------------------");
        console.log('tripData[]: ');
        tripData.forEach(function (s) {
            console.log(s);
        });

        console.log('trackingData[]: ');
        trackingData.forEach(function (s) {
            console.log(s);
        });


        function initMap() {
            var directionsService = new google.maps.DirectionsService();
            var directionsDisplay = new google.maps.DirectionsRenderer();
            var start = new google.maps.LatLng(tripData[0].lat, tripData[0].lng);
            var end = new google.maps.LatLng(tripData[tripData.length-1].lat, tripData[tripData.length-1].lng);

            var mapOptions = {
                zoom: 3,
                center: start
            }
            var map = new google.maps.Map(document.getElementById('map'), mapOptions);
            directionsDisplay.setMap(map);
            calculateAndDisplayRoute(directionsService, directionsDisplay);
            //calcRoute();
            var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/'; //'https://www.fetchmygoods.com/images/';
            var icons = {
                parking: {
                    icon: iconBase + 'parking_lot_maps.png'
                },
                library: {
                    icon: iconBase + 'library_maps.png'
                },
                info: {
                    icon: iconBase + 'info-i_maps.png'
                }
            };

            //features.forEach(function (feature) {
            //    var marker = new google.maps.Marker({
            //        position: feature.position,
            //        icon: icons[feature.type].icon,
            //        map: map
            //    });
            //});


            // The below segment of code is for drawing a dotted line from start to destination wtih all the waypoints included:
            // Define a symbol using SVG path notation, with an opacity of 1.
            if (trackingData != null) {
                if (trackingData.length > 0) {

                    var features = [];
                    $.each(trackingData, function (key, CoOrdinates) {
                        features.push({
                            position: new google.maps.LatLng(CoOrdinates.lat, CoOrdinates.lng),
                            type: 'info'
                        });
                    });

                    //  var features = [
                    //{
                    //    position: new google.maps.LatLng(13.0827, 80.2707),
                    //    type: 'parking'
                    //},
                    //{
                    //    position: new google.maps.LatLng(11.20, 77.46),
                    //    type: 'parking'
                    //},
                    //{
                    //    position: new google.maps.LatLng(8.0883, 77.5385),
                    //    type: 'parking'
                    //}
                    //  ];

                    var infowindow = new google.maps.InfoWindow({
                        content: 'Hello World!',
                        map: map
                    });

                    //var Currentmarker = new google.maps.Marker({
                    //    position: features[features.length - 1].position,
                    //    icon: icons['parking'].icon,
                    //    map: map
                    //});

                    var marker, i;

                    for (i = 0; i < trackingData.length; i++) {
                        marker = new google.maps.Marker({
                            position: new google.maps.LatLng(trackingData[i].lat, trackingData[i].lng),
                            map: map,
                            icon: icons[features[features.length - 1].type].icon,
                        });

                        google.maps.event.addListener(marker, 'mouseover', (function (marker, i) {
                            return function () {
                                infowindow.setContent(trackingData[i].msg);
                                infowindow.open(map, marker);
                            }
                        })(marker, i));
                        google.maps.event.addListener(marker, 'mouseout', (function (marker, i) {
                            return function () {
                                infowindow.close();
                            }
                        })(marker, i));
                    }



                    var lineSymbol = {
                        path: 'M 0,-1 0,1',
                        strokeOpacity: 1,
                        scale: 4
                    };

                    // Create the polyline, passing the symbol in the 'icons' property.
                    // Give the line an opacity of 0.
                    // Repeat the symbol at intervals of 20 pixels to create the dashed effect.
                    var line = new google.maps.Polyline({
                        path: trackingData, //[{ lat: 13.0827, lng: 80.2707 }, { lat: 11.20, lng: 77.46 }, { lat: 8.0883, lng: 77.5385 }],
                        strokeOpacity: 0,
                        icons: [{
                            icon: lineSymbol,
                            offset: '0',
                            repeat: '30px'
                        }],
                        map: map
                    });
                }
            }

        }

        function calculateAndDisplayRoute(directionsService, directionsDisplay) {
            var selectedMode = "DRIVING"; //document.getElementById('mode').value;
            var waypts = [];
            for (var i = 1; i < tripData.length-1; i++) {
                waypts.push({
                    location: new google.maps.LatLng(tripData[i].lat, tripData[i].lng),
                    stopover: false
                });
            }

            var request = {
                origin: new google.maps.LatLng(tripData[0].lat, tripData[0].lng),
                destination: new google.maps.LatLng(tripData[tripData.length - 1].lat, tripData[tripData.length - 1].lng),
                waypoints: waypts,
                optimizeWaypoints: true,
                travelMode: google.maps.DirectionsTravelMode.DRIVING
            };

            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                    var route = response.routes[0];
                    var summaryPanel = document.getElementById("directions_panel");
                    summaryPanel.innerHTML = "";
                    // For each route, display summary information.
                    for (var i = 0; i < route.legs.length; i++) {
                        var routeSegment = i + 1;
                        summaryPanel.innerHTML += "<b>Route Segment: " + routeSegment + "</b><br />";
                        summaryPanel.innerHTML += route.legs[i].start_address + " to ";
                        summaryPanel.innerHTML += route.legs[i].end_address + "<br />";
                        summaryPanel.innerHTML += route.legs[i].distance.text + "<br /><br />";
                    }
                    summaryPanel.innerHTML = "";
                } else {
                    console.log("directions response " + status);
                }
            });
        }

</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5oZ_wJYhvvQRhwNOVEUTohDnPTYyOXuA&callback=initMap">
</script>
<style>
    .google-maps {
        position: relative;
        padding-bottom: 75%;
        height: 0;
        overflow: hidden;
    }

        .google-maps iframe {
            position: relative;
            top: 0;
            left: 0;
            width: 100% !important;
            height: 100% !important;
        }
</style>

<div class="google-maps" id="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d7098.94326104394!2d78.0430654485247!3d27.172909818538997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1385710909804" width="600" height="450" frameborder="0" style="border:0"></iframe>
</div>
<div id="directions_panel"></div>